rht-4571 added new process empEmployement
axonivy-market/successfactors-connector pull request #55
Opened 2024-09-17 11:26 UTC by kamilkhan1311

please review and approve.

2024-09-17 11:28 UTC, JoaoPedroCarvalho commented
Hi @nqhoan-axonivy , 
@kamilkhan1311 Added a new service call to successfactors. please approve and merge it so we can use it in HR application

2024-10-08 08:54 UTC, ndkhanh-axonivy requested changes
Hi @kamilkhan1311 , could you please check my comments, thank you!

2024-10-08 08:54 UTC, ndkhanh-axonivy commented on successfactors-connector/dataclasses/connector/EmpEmploymentData.ivyClass
Could you please remove all persistent check here
![image](https://github.com/user-attachments/assets/75a75baa-313b-4a52-85bd-6db4307fcbcd)

2024-10-08 08:54 UTC, ndkhanh-axonivy commented on successfactors-connector/processes/connector/EmpEmployment.p.json
> +          "$expand" : ""
please add assign value for the expand

2024-10-08 08:54 UTC, ndkhanh-axonivy commented on successfactors-connector/processes/connector/EmpEmployment.p.json
> +            { "name" : "id", "type" : "String" }
Why do we need to add the id field? I don't see any usage for it. If it's not necessary, could you please remove it?

2024-10-08 08:54 UTC, ndkhanh-axonivy commented on successfactors-connector/processes/connector/EmpEmployment.p.json
![image](https://github.com/user-attachments/assets/e69eb493-621c-4d17-a5a2-54c468c53702)

Please right click on the Rest Client element and choose this option
![image](https://github.com/user-attachments/assets/83cbc1be-d321-4c47-88ae-8b07b32974d2)

2024-10-10 03:00 UTC, ndkhanh-axonivy commented
Hi @JoaoPedroCarvalho, because you're waiting on this so we just want to provide an update that we added some new comments 2 days ago, and we're currently awaiting feedback from @kamilkhan1311

2024-10-10 05:56 UTC, kamilkhan1311 commented
Hi @ndkhanh-axonivy I am working on changes today will commit it.

2024-10-10 07:50 UTC, ndkhanh-axonivy commented on successfactors-connector/processes/connector/EmpEmployment.p.json
Hi @kamilkhan1311 , could also map the error for Error Boundary Event
![image](https://github.com/user-attachments/assets/5216d7ba-3d94-4d90-a3bf-9d9249763043)

2024-10-10 08:07 UTC, kamilkhan1311 commented on successfactors-connector/processes/connector/EmpEmployment.p.json
done.

2024-10-10 08:09 UTC, ndkhanh-axonivy approved these changes
LGTM

2024-10-10 08:10 UTC, merged

2024-10-10 08:31 UTC, ndkhanh-axonivy commented
Hi @JoaoPedroCarvalho and @kamilkhan1311, the new version of SuccessFactors is now available. Please use it by updating the version to 10.0.19. Thank you for your contributions!

FYI, @ivy-sgi.